### ISSUE TITLE
Add unsecure option to backend adaptor

### ISSUE THREAD

**Issue by SeungheonOh** [mlabs-haskell/cardano-dev-wallet#13]
Currently it expects kupogmios to be secure. It would be nice to add option to enable/disable secure connection to kupogmios for instances running in local machine/instances on VPN

**Comment by itsfarseen** [comment]
@SeungheonOh you can specify the protocol explicitly like `http://localhost`.
Only if `http://` is omitted, the wallet assumes `https://`.

**Comment by SeungheonOh** [comment]
Ah! that makes sense. Thank you.
